### ISSUE TITLE
Does 'css-tools' handle pseudo-elements?

### ISSUE THREAD

**Issue by tgraham-antenna** [transpect/css-tools#10]
Is 'css-tools' expected to handle pseudo-element selectors that contain `::`?

This document:

```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
p::before {
  content: 'H';
  color: green;
}
</style>
<body>
<p>ello, world</p>
</body>
</head>
```

run through pipelines modified for use with MorganaXProc-IIIse but with an unmodified `REx_css-parser.xsl` generates this output:

```
morgana workspace/test-css-expand.xpl  -input:source=css-tools/test.html -output:result=out/test.html -output:xml-representation=xml-representation/test.xml
=================================
MorganaXProc-IIIse 0.9.12-beta
Copyright 2011-2022 by <xml-project /> Achim Berndzen
=================================

Using Saxon-HE 9.9.1.5. XSLT and XQuery processor developed by Saxonica Limited
<c:errors xmlns:c="http://www.w3.org/ns/xproc-step"><c:error code="err:XC0093" cause="Unknown error" name="!2.4" type="p:xslt" href="file:/.../workspace/css.xpl" line="165" column="13" xmlns:p="http://www.w3.org/ns/xproc" xmlns:err="http://www.w3.org/ns/xproc-error"><message>Error 'Unknown error': Fatal error: Unexpected token ":" beyond end of expression; SystemID: file:///.../css-tools/test.html; Line#: -1; Column#: 3
Fatal error: Unexpected token name "H" beyond end of expression; SystemID: file:///.../css-tools/test.html; Line#: -1; Column#: -1. (unknown source at -1/-1)</message></c:error></c:errors>
```

**Comment by gimsieke** [comment]
The grammar at least contains pseudo, https://github.com/transpect/css-tools/blob/master/ebnf-scheme/CSS3.ebnf#L39
I will investigate.

**Comment by tgraham-antenna** [comment]
I had seen that, and it was my first thought as the likely cause, but my REx-fu isn't good enough for me to want to tinker with it. (My REx experience is that it involves a lot of trial and a lot of error before I get it right.)

**Comment by gimsieke** [comment]
The single quotes in `'H'` needed some escaping, please pull and try again.

**Comment by tgraham-antenna** [comment]
The 'H' problem is fixed, thank you, but I still get `Unexpected token ":" beyond end of expression`.

**Comment by gimsieke** [comment]
Ah, I didn’t notice this error in the message (I didn’t scroll to the right this far). 

That happened to me, too, but only when I used the [old, regex-based parser](https://github.com/transpect/css-tools/blob/master/xsl/css-parser.xsl). This parser apparently can handle only a single colon with the pseudo selector. I switched the default parser to REx_css-parser.xsl in [test-css-expand.xpl](https://github.com/transpect/css-tools/blob/master/xpl/test-css-expand.xpl#L12) and this parses fine. With `debug=yes`, I get this as css-expand/css.1.parse.xml in `$debug-dir-uri`:

```xml
<parser-results xmlns:css="http://www.w3.org/1996/css"
                xmlns:html="http://www.w3.org/1999/xhtml"
                xmlns:p="CSS3"
                xmlns:tr="http://transpect.io"
                xmlns:xslout="bogo"
                xml:base="file:/mnt/c/Users/gerrit/Dev/epubtools-xproc/Untitled8.xhtml">
   <css origin="file://internal">
      <S>
</S>
      <rule>
         <selectors_group>
            <selector>
               <simple_selector_sequence>
                  <type_selector>
                     <element_name>
                        <IDENT>p</IDENT>
                     </element_name>
                  </type_selector>
                  <pseudo>
                     <TOKEN>:</TOKEN>
                     <TOKEN>:</TOKEN>
                     <IDENT>before</IDENT>
                  </pseudo>
               </simple_selector_sequence>
            </selector>
         </selectors_group>
         <S> </S>
         <TOKEN>{</TOKEN>
         <S>
  </S>
         <declaration>
            <property>
               <IDENT>content</IDENT>
            </property>
            <TOKEN>:</TOKEN>
            <S> </S>
            <values>
               <value>
                  <QUOTED_STRING>
                     <TOKEN>'</TOKEN>
                     <STRING_CONTENT2>H</STRING_CONTENT2>
                     <TOKEN>'</TOKEN>
                  </QUOTED_STRING>
               </value>
            </values>
         </declaration>
         <TOKEN>;</TOKEN>
         <S>
  </S>
         <declaration>
            <property>
               <IDENT>color</IDENT>
            </property>
            <TOKEN>:</TOKEN>
            <S> </S>
            <values>
               <value>
                  <IDENT>green</IDENT>
               </value>
            </values>
         </declaration>
         <TOKEN>;</TOKEN>
         <S>
</S>
         <TOKEN>}</TOKEN>
      </rule>
      <S>
</S>
   </css>
</parser-results>
```

and this as css-expand/css.2.xml-representation.xml

```xml
<css xmlns="http://www.w3.org/1996/css"
     xmlns:css="http://www.w3.org/1996/css"
     xmlns:html="http://www.w3.org/1999/xhtml"
     xmlns:p="CSS3"
     xmlns:tr="http://transpect.io"
     xmlns:xslout="bogo">
   <ruleset origin="file://internal">
      <raw-css xml:space="preserve">
        p::before {
  content: 'H';
  color: green;
}
      </raw-css>
      <selector priority="0,0,0,2"
                position="1"
                raw-selector="p::before"
                pseudo="before">*:p[. [@css:pseudo_before]]</selector>
      <declaration property="content" value="'H'"/>
      <declaration property="color" value="green"/>
   </ruleset>
</css>
```

If you use the old parser, you should see something like `*:p: [@css:pseudo_before]` which causes the error when the generated XSLT is compiled.

**Comment by tgraham-antenna** [comment]
Sorry about that.  I had changed it in `css.xpl`, but (now) obviously not in the override in `test-css-expand.xpl`.

However, the `::before` didn't add any `css:*` attributes in the output, so does 'css-tools' handle pseudos or not?

**Comment by gimsieke** [comment]
I’m afraid it doesn’t. It just produces XSLT patterns that don’t match since there are no `@css:pseudo_before` attributes to match. I think this needs some more consideration. I don’t know why we implemented it this way. I suspect that pseudos weren’t a major concern so far. Let me see whether I can adapt css2xsl.xsl in a useful way.

Aside: From time to time we need the old parser (for fixed-layout EPUBs with some 15,000 lines of CSS, since the REx-generated parser is too slow for this), therefore I’m currently trying to teach it to handle double colons correctly.

**Comment by gimsieke** [comment]
Some progress already wrt dealing with before/after pseudos. Will continue later today or tomorrow.

**Comment by tgraham-antenna** [comment]
Thanks for following up with this. However, I found this issue because of `::first-letter` and `::first-line` pseudos. Will they be handled?

**Comment by gimsieke** [comment]
Yes, I think all of them will end up in some css-namespaced attribute.

**Comment by gimsieke** [comment]
I improved the pseudo handling. Currently only `first-child` will be translated into an XSLT pattern predicate. The others just match the base elements, like `p`, and will encode all pseudo properties as attributes. Example:

```css
div.foo p::first-letter {
  content: 'H';
  color: green;
}
div.foo p:first-child {
  foo: bar;
  color: blue;
}
div.foo p {
  color: red;
}
```

```html
<body>
  <div class="foo">
    <p>ello, world</p>
  </div>
</body>
```

```xml
<p css:foo="bar" css:color="blue" css:pseudo-first-letter_content="'H'" css:pseudo-first-letter_color="green">ello, world</p>
```

**Comment by tgraham-antenna** [comment]
Works for me, thank you.
