### ISSUE TITLE
Fails with url(#foo)

### ISSUE THREAD

**Issue by AirQuick** [transpect/css-tools#3]
If CSS has such lines as

```css
marker-start: url(#markerCircle);
marker-end: url(#markerArrow);
```

which can quite happen with SVG, the parser fails:

```
ERROR: .../css-tools/xsl/REx_css-parser.xsl:682:p:parse-css:
    lexical analysis failed
    while expecting HEX
    after successfully scanning 1 characters beginning at line 4, column 38:
    ...#markerCircle);
                       marker-end: url(#markerArrow)...
```

**Comment by gimsieke** [comment]
Maybe the [current grammar](https://github.com/transpect/css-tools/blob/master/ebnf-scheme/CSS3.ebnf#L53) won’t accept '`#`' in `url()`. We’ll look into it.

**Comment by gimsieke** [comment]
I hopefully solved it; also added such a URL to [example.html](https://github.com/transpect/css-tools/blob/f29e4e79a8056842afbe29bbfedc1d34666a1488/example/style.css#L25).

**Comment by AirQuick** [comment]
Yes, it works. Thanks for the update.
