### ISSUE TITLE
Analysis fails with rem

### ISSUE THREAD

**Issue by AirQuick** [transpect/css-tools#4]
This `1.7em`

```html
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>css-expand example</title>
    <style type="text/css">
      p {margin-bottom:1.7em}
    </style>
  </head>
  <body>
    <p>Ttext</p>
  </body>
</html>
```

is expanded successfully

```html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:css="http://www.w3.org/1996/css">
  <head>
    <title>css-expand example</title>
    <style type="text/css">
      p {margin-bottom:1.7em}
    </style>
  </head>
  <body>
    <p css:margin-bottom="1.7em">Ttext</p>
  </body>
</html>
```

but this `1.7rem`

```html
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>css-expand example</title>
    <style type="text/css">
      p {margin-bottom:1.7rem}
    </style>
  </head>
  <body>
    <p>Ttext</p>
  </body>
</html>
```

fails

```console
Message:
    lexical analysis failed
    while expecting [S, ':']
    at line 2, column 30:
    ...}
```

**Comment by gimsieke** [comment]
Yes, someone needs to expand the [grammar](https://github.com/transpect/css-tools/blob/master/ebnf-scheme/CSS3.ebnf#L115) and re-generate the [XSLT](https://github.com/transpect/css-tools/blob/master/xsl/CSS3.xsl). There will be other stuff that won’t parse despite being specified in the CSS specs.

**Comment by AirQuick** [comment]
Shall I update the grammar (only for this specific issue), re-generate CSS3.xsl using https://www.bottlecaps.de/rex/ with [the written command line](https://github.com/transpect/css-tools/blob/ae7727a3c36b825ae6829fdf6e589471b77708d7/xsl/CSS3.xsl#L3) and submit a pull request?

**Comment by gimsieke** [comment]
That would be great. 
Unfortunately, we don’t have public CI tests for this repo, but I will likely accept the PR and then run our internal tests.
