### ISSUE TITLE
'bold' should be 'normal' in 'example.xhtml'

### ISSUE THREAD

**Issue by tgraham-antenna** [transpect/css-tools#9]
https://github.com/transpect/css-tools/blob/7652f081acebff2003b9ddcd71c10a92125eed36/example/example.xhtml#L82-L85

from:

https://github.com/transpect/css-tools/blob/7652f081acebff2003b9ddcd71c10a92125eed36/example/style.css#L18-L21

**Comment by gimsieke** [comment]
The result corresponds to [style.css as of 2017-11](https://github.com/transpect/css-tools/blob/a750aa1c). Somone changed style.css without modifying the output accordingly. I think I’m going to change it back to bold.
